[project]
name = "finance-quote-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
]
